### ISSUE TITLE
Authentification

### ISSUE THREAD

**Issue by Ankirama** [Ankirama/ios_project#1]
# Todo

- [ ] : Inscription firebase
- [ ] : Connexion firebase
- [ ] : Connexion Facebook
- [ ] : Connexion Google+

# Détails

### Model

- [ ] : email (unique, lowercase)
- [ ] : password (minimum 8 characteres)
- [ ] : image (photo de profil - url / base64 a voir)
- [ ] : fullname (Capitalized : chaque mot a une majuscule)
- [ ] : description
- [ ] : facebook_id
- [ ] : google_plus_id

## Connexion Firebase

Connexion avec email / password

- Vérifier email valide
- Vérifier password taille >= 8

## Connexion Facebook

Si connexion OK voir si un compte avec le mail utilisé existe déjà ou si un compte avec le même facebook_id existe

## Connexion Google+

Voir [facebook](#connexion-facebook) 

# Images

- [View](https://github.com/fredfoc/EpitechEisenhower/blob/master/graphics/export_screens/Login%20Screen.png)
