### ISSUE TITLE
Page de profil - besoin d'être connecté

### ISSUE THREAD

**Issue by Ankirama** [Ankirama/ios_project#2]
# Todo

- [ ] : Récupérer les informations sur firebase si pas en cache
- [ ] : Afficher image (framework alamofireimage)
- [ ] : Bouton pour sauvegarder les changements
- [ ] : Bouton pour renew password
- [ ] : Bouton pour logout

# Détails

## Récupérer les informations

- Vérifier le cache, si pas de login / user data on consume firebase
- Récupérer les informations `/users/me` sur firebase avec [Alamofire](https://github.com/Alamofire/Alamofire)

## Image

Le framework [AlamofireImage](https://github.com/Alamofire/AlamofireImage) permettra de récupérer l'image, il faudra en revanche s'assurer de la taille

## Sauvegarder les changements

- Les champs devront être éditables
- En modifiant on mettra en jour le cache + firebase

## Reset password

- Il faudra demander l'ancien password + 2 x le nouveau (en vérifiant si c'est les 2 sont OK)
- Envoyer la modification sur firebase

## Logout

- Clear cache
- Redirection page d'authentification

# Screenshots

- [Fonts](https://github.com/fredfoc/EpitechEisenhower/blob/master/graphics/export_screens/Profile%20Screen%20Font.png)
- [View](https://github.com/fredfoc/EpitechEisenhower/blob/master/graphics/export_screens/Profile%20Screen.png)
