### ISSUE TITLE
Home page - besoin d'être connecté

### ISSUE THREAD

**Issue by Ankirama** [Ankirama/ios_project#3]
# Todo

- [ ] : Afficher tasks
- [ ] : Trier tasks par ordre d'importance / urgence
- [ ] : Bouton pour ajouter une task
- [ ] : Bouton pour accéder au profil
- [ ] : Pouvoir cliquer sur une task et l'éditer (voir ajout)

# Détails

## Afficher tasks

- Il faut pouvoir afficher les tasks de la personne ET des tasks ou il est en collaboration

## Trier tasks

- Les tasks devront être triées en fonction d'Einsenhower puis par date

## Ajouter task

- Voir autre issue

## Accéder profil

- Un bouton doit permettre d'accéder à la page profil de l'utlisateur

# Images

- [Fonts](https://github.com/fredfoc/EpitechEisenhower/blob/master/graphics/export_screens/FontAndColors.png)
- [View](https://github.com/fredfoc/EpitechEisenhower/blob/master/graphics/export_screens/Home%20Screen.png)
