### ISSUE TITLE
Ajouter une tache

### ISSUE THREAD

**Issue by Ankirama** [Ankirama/ios_project#4]
# Todo

- [ ] : Définir le type (urgent / pas urgent + important / pas important)
- [ ] : Titre de la tache
- [ ] : Collaborateurs (ajout / suppresion - en appuyant sur la personne + confirmation)
- [ ] : Description de la tache
- [ ] : Date où la tache doit être OK (optionnel)
- [ ] : Bouton pour valider la création (ou la modification)
- [ ] : Bouton pour supprimer la tache + confirmation

# Images

- [Font](https://github.com/fredfoc/EpitechEisenhower/blob/master/graphics/export_screens/Task%20Detail%20Screen%20Font.png)
- [View](https://github.com/fredfoc/EpitechEisenhower/blob/master/graphics/export_screens/Task%20Detail%20Screen.png)
